secrets:
  minio_user:
    file: ./secrets/minio_user.txt
  minio_password:
    file: ./secrets/minio_password.txt

services:
  redis:
    image: redis:8.6.1-alpine3.23
    ports:
      - "6379:6379"
    # redis-server --save "" --appendonly no
    # désactive la persistance sur disque → Redis utilisé uniquement comme cache RAM
    command: redis-server --save "" --appendonly no

  optimizer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: optimizer
        CMD_PATH: /usr/local/bin/optimizer
    ports:
      - "3001:3001"

  rabbitmq:
    image: rabbitmq:4.2.4-alpine
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      # rabbitmq.conf est dans secrets/ (gitignorés) — contient default_user et default_pass
      - ./secrets/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: api
        CMD_PATH: /usr/local/bin/api
    ports:
      - "4000:4000"
    environment:
      - OPTIMIZER_URL=http://optimizer:3001
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
    secrets:
      - minio_user
      - minio_password

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # _FILE : MinIO lit le contenu du fichier monté par Docker secrets
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_password
    secrets:
      - minio_user
      - minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  front:
    build: ./front
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  minio_data:
